=== GeorgeAlexandrakis93/XML/Part 2/ΕΡΩΤΗΜΑ 2.5/TouristGuide_New2.dtd
<?xml version="1.0" encoding="ISO-8859-7" ?>

<!ELEMENT Root_Element (Touristic_Location*)>
<!ELEMENT Touristic_Location (Location_Name, Description, Monuments, Arounds, Beaches?, Routing, Useful_Phones, Location_Climate, Cost_Level, Info, Voting)>
<!ELEMENT Location_Name (#PCDATA)>
<!ELEMENT Description (#PCDATA | Local_Products | Cultural_Events)*>
<!ELEMENT Local_Products (Prod_Name+)>
<!ELEMENT Prod_Name (#PCDATA)>
<!ELEMENT Cultural_Events (Event*)>
<!ELEMENT Event (#PCDATA)>
<!ELEMENT Monuments (Mon_Name+)>
<!ELEMENT Mon_Name (#PCDATA)>
<!ELEMENT Arounds (Around)>
<!ELEMENT Around (#PCDATA)>
<!ELEMENT Beaches (Beach+)>
<!ELEMENT Beach (#PCDATA)>
<!ELEMENT Routing (Distance+)>
<!ELEMENT Distance (Routes?)>
<!ELEMENT Routes (Route*)>
<!ELEMENT Route (#PCDATA)>
<!ELEMENT Useful_Phones (Service_Phone*)>
<!ELEMENT Service_Phone ((Serv_Name, Phone) | (Phone, Serv_Name))>
<!ELEMENT Serv_Name (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Location_Climate EMPTY>
<!ELEMENT Cost_Level EMPTY>
<!ELEMENT Info (Area, Population)>
<!ELEMENT Area (#PCDATA)>
<!ELEMENT Population (#PCDATA)>
<!ELEMENT Voting (Vote+)>
<!ELEMENT Vote EMPTY>
<!ATTLIST Event 
	Date CDATA #REQUIRED
	Event_Desc CDATA #IMPLIED>
<!ATTLIST Mon_Name Name CDATA #REQUIRED>
<!ATTLIST Around Name CDATA #REQUIRED>
<!ATTLIST Beach Name CDATA #REQUIRED>
<!ATTLIST Distance
	From CDATA #REQUIRED
	Value CDATA #REQUIRED
	Unit CDATA #FIXED "χλρ">
<!ATTLIST Location_Climate
	Sum_Tempr_Perc CDATA #IMPLIED
	Moist_Perc CDATA #REQUIRED>
<!ATTLIST Cost_Level 
	Level (1 | 2 | 3 | 4 | 5) #IMPLIED>
<!ATTLIST Vote
	Username CDATA #IMPLIED
	Stars CDATA #REQUIRED
	Comment CDATA #IMPLIED>

=== GeorgeAlexandrakis93/XML/Part 2/ΕΡΩΤΗΜΑ 2.5/TouristGuide_New2.xml
<?xml version="1.0" encoding="ISO-8859-7" ?>
<!DOCTYPE Root_Element SYSTEM "TouristGuide_New2.dtd">

<Root_Element>
	<Touristic_Location>
		<Location_Name> Ξυλόκαστρο </Location_Name>
		<Description> Η παραθαλάσσια πόλη του Ξυλοκάστρου είναι έδρα του δήμου Ξυλοκάστρου  Ευρωστίνης και ανήκει στην περιφερειακή ενότητας Κορινθίας. Το όνομά του το πήρε από ένα ξύλινο στρατώνα που λειτουργούσε ως παρατηρητήριο στην περιοχή, κατά τα χρόνια της Ενετοκρατίας. Ο στρατώνας βρισκόταν πάνω από τη σημερινή πόλη, κοντά στον ποταμό Σύθα. Κάθε καλοκαίρι δέχεται χιλιάδες επισκέπτες. Αποτελεί ιδανικό προορισμό τόσο για διακοπές σαββατοκύριακου, όσο και για πολυήμερες διακοπές. Στο Ξυλόκαστρο υπάρχουν πολλά ξενοδοχεία, ταβέρνες και καφέ, που αποτελούν πόλο έλξης των παραθεριστών. 
			<Local_Products>
				<Prod_Name> φρέσκα θαλασσινά, </Prod_Name>
				<Prod_Name> κρεατικά, </Prod_Name>
				<Prod_Name> ουζομεζέδες, και </Prod_Name>
				<Prod_Name> ψητά σούβλας </Prod_Name>
			</Local_Products>
		</Description>
		<Monuments>
			<Mon_Name Name="Δάσος Πευκιά"> Το Δάσος του Πευκιά βρίσκεται στο ανατολικό άκρο του Ξυλοκάστρου, ανάμεσα στο Ξυλόκαστρο και τη Συκιά. Είναι ένα φυσικό πευκοδάσος μήκους 1760 μέτρων ηλικίας άνω των 140 ετών. Έχει χαρακτηριστεί από τον Καρυωτάκη σε ποιημά του ως το «πράσινο ακρογιάλι της πατρίδας». Αποτελούσε επίσης πηγή έμπνευσης του ’γγελου Σικελιανού. Είναι ένα ιδανικός σημείο για περπάτημα και τρέξιμο απολαμβάνοντας ταυτόχρονα τις μυρωδιές από τα κάθε λογής λουλούδια και φυτά. </Mon_Name>
			<Mon_Name Name="Μονή της Παναγίας Κορφιώτισσας">  Η Μονή της Παναγιάς Κορφιώτισσας, βρίσκεται νότια του χωριού Καμάρι του δήμου Ξυλοκάστρου. Βρίσκεται σε υψόμετρο 730 περίπου μέτρων, στην κορυφή του λόφου «Κούτσα». Η θέα από το σημείο αυτό είναι μοναδική. Η ιστορία αναφέρει ότι αρχικά χτίστηκε ένα μικρό εκκλησάκι στα ερείπια αρχαίου κτίσματος και στη συνέχεια το μοναστήρι. Το μοναστήρι αρχικά φιλοξενούσε άνδρες μοναχούς αλλά αργότερα μετατράπηκε σε γυναικείο. Η εικόνα της Παναγιάς της Κορφιώτισσας, που χρονολογείται από το 1816, είναι τοποθετημένη σε σκαλιστό εικονοστάσι, έργο του ξυλογράφου Ιωάννου Βασιλείου. </Mon_Name>
		</Monuments>
		<Arounds>
			<Around Name="Τρίκαλα Κορινθίας"> Ανηφορίζοντας από Ξυλόκαστρο σε απόσταση 20 χλμ βρίσκονται τα Τρίκαλα Κορινθίας. Τα Τρίκαλα Κορινθίας είναι φωλιασμένα στις πλαγιές του οροπεδίου της Ζήρειας και αποτελούνται από τρεις συνοικίες τα Κάτω Τρίκαλα Κορινθίας, τα Μεσαία Τρίκαλα Κορινθίας και τα ’νω Τρίκαλα Κορινθίας. Παραμένει μια παραδοσιακή περιοχή με πέτρινες πλατείες και αιωνόβια πλατάνια που θα σας εκπλήξει με τις σπάνιες ομορφιές της, τα βουνά, τα γάργαρα νερά, το χιόνι που σε συνδυασμό με την πέτρα και το ξύλο και τη φιλοξενία των κατοίκων της δημιουργούν ένα ήρεμο και γαλήνιο τοπίο που θα κάνει την διαμονή σας αξέχαστη. </Around>
		</Arounds>
		<Beaches>
			<Beach Name="Παραλία Πευκία"> Μπρόστα από το Δάσος του Πευκιά επεκτείνετε η παραλία του Πευκιά, μία παραλία με καταγάλανα καθαρά νερά και μεγάλα βότσαλα. Πρόκειται για μία οργανωμένη παραλία με ξαπλώστρες και ομπρέλες, με μεγάλη επισκεψιμότητα λόγο της φήμης της. </Beach>
			<Beach Name="Παραλία Αριστοναυτών"> Η παραλία των Αριστοναυτών είναι αμμώδης και αρκετά ήσυχη καθώς δεν είναι οργανωμένη. </Beach>
			<Beach Name="Παραλία Συκίας"> Στη συνέχεια του Ξυλοκάστρου θα βρείτε το χωριό Συκία και την ομώνυμη παραλία του. Κι εδώ θα βρείτε επίσης βότσαλο και καθαρά νερά. </Beach>
		</Beaches>
		<Routing>
			<Distance From="Αθήνα" Value="120">
				<Routes>
					<Route> Από την Αθήνα μπορείτε να φτάσετε στο Ξυλόκαστρο αν ακολουθήσετε την Ε.Ο. Αθηνών-Κορίνθου-Πατρών. </Route>
					<Route> Καθημερινά εκτελούνται δρομολόγια του ΚΤΕΛ από την Αθήνα. </Route>
				</Routes>
			</Distance>
			<Distance From="Πάτρα" Value="95">
				<Routes>
					<Route> Από την Πάτρα μπορείτε να φτάσετε στο Ξυλόκαστρο αν ακολουθήσετε την Ε.Ο. Πατρών-Κορίνθου.  </Route>
					<Route> Καθημερινά εκτελούνται δρομολόγια του ΚΤΕΛ από την Πάτρα. </Route>
				</Routes>
			</Distance>
		</Routing>
		<Useful_Phones>
			<Service_Phone>
				<Serv_Name> Δήμος Ξυλοκάστρου </Serv_Name>
				<Phone> 27433 60200 </Phone>
			</Service_Phone>
			<Service_Phone>
				<Serv_Name> Κέντρο Υγείας Ξυλοκάστρου </Serv_Name>
				<Phone> 27433 60000 </Phone>
			</Service_Phone>
			<Service_Phone>
				<Serv_Name> Νοσοκομείου Κορινθίου </Serv_Name>
				<Phone> 27410 25711 </Phone>
			</Service_Phone>
			<Service_Phone>
				<Serv_Name> Δασαρχείο </Serv_Name>
				<Phone> 27430 22282 </Phone>
			</Service_Phone>
			<Service_Phone>
				<Serv_Name> Αστυνομία Ξυλοκάστρου </Serv_Name>
				<Phone> 27430 29232 </Phone>
			</Service_Phone>
			<Service_Phone>
				<Serv_Name> Τροχαία Ξυλοκάστρου </Serv_Name>
				<Phone> 27430 29227 </Phone>
			</Service_Phone>
		</Useful_Phones>
		<Location_Climate Sum_Tempr_Perc="35" Moist_Perc="30"/>
		<Cost_Level Level="3"/>
		<Info>
			<Area> 310,3 km2 </Area>
			<Population> 15.273 </Population>
		</Info>
		<Voting>
			<Vote Username="ironman2" Stars="5" Comment="Υπέροχος προορισμός"/>
			<Vote Username="mcu2000" Stars="4" Comment="'Ομορφα τοπία"/>
		</Voting>
	</Touristic_Location>
	<Touristic_Location>
		<Location_Name> Πύλος </Location_Name>
		<Description> Η Πύλος είναι μία μικρή γραφική παραθαλάσσια πόλη, που βρίσκεται στο νοτιοδυτικό τμήμα του νομού Μεσσηνίας.  Η Πύλος είναι αμφιθεατρικά χτισμένη στο νότιο άνοιγμα του όρμου του Ναβαρίνου, όπου έγινε η ιστορική ναυμαχία, και ορίζεται από τη νήσο Σφακτηρία. Η Πύλος αποτελεί το μεγαλύτερο φυσικό λιμάνι της Πελοποννήσου και ταυτόχρονα έναν από τους πιο ενδιαφέροντες τουριστικούς προορισμούς της Μεσσηνίας, χάρη στην ένδοξη ιστορία και τις πλούσιες φυσικές ομορφιές της περιοχής. Η κωμόπολη της Πύλου έχει ένα νησιωτικό χαρακτήρα. Η Πύλος προσελκύει κάθε καλοκαίρι πολλούς τουρίστες, που την επισκέπτονται για να θαυμάσουν τα ιστορικά της μνημεία και τη γραφικότητα του τοπίου.
			<Local_Products>
				<Prod_Name> τηγανιτός βακαλάος με σκορδαλιά, </Prod_Name>
				<Prod_Name> δίπλες, </Prod_Name>
				<Prod_Name> λουκάνικα καπνισμένα, </Prod_Name>
				<Prod_Name> λαλάγγια και </Prod_Name>
				<Prod_Name> ούζο </Prod_Name>
			</Local_Products>
			<Cultural_Events>
				<Event Date="Πρώτο δεκαπενθήμερο του Αυγούστου" Event_Desc="Αγωνίσματα στίβου και θάλασσας, όπως κολύμβηση, ιστιοπλοΐα κ.ά."> Τσικλιτήρια </Event>
				<Event Date="23 Σεπτεμβρίου"> Πανηγύρι της Παναγίας της Γοργοπηγής </Event>
				<Event Date="20 Οκτωβρίου"> Επέτειος της Ναυμαχίας του Ναβαρίνου </Event>
			</Cultural_Events>
		</Description>
		<Monuments>
			<Mon_Name Name="Η πλατεία Τριών Ναυάρχων"> Βρίσκεται στο κέντρο της Πύλου αποτελεί πραγματικό αξιοθέατο για την πόλη. Στην πλατεία δεσπόζει το ομώνυμο μνημείο, προς τιμήν των Ναυάρχων Κόδριγκτων, Δεριγνύ, Χέυδεν, που ηγήθηκαν της ιστορικής ναυμαχίας του Ναβαρίνου. Αριστερά και δεξιά από το μνημείο βρίσκονται δύο ορειχάλκινα κανόνια, ένα βενετσιάνικο και ένα τούρκικο, που μεταφέρθηκαν από το φρούριο του Νιόκαστρου. Στην πλατεία Τριών Ναυάρχων μπορείτε να απολαύσετε τον καφέ σας υπό τη σκιά και δροσιά των εντυπωσιακών αιωνόβιων πλατάνων, απολαμβάνοντας ταυτόχρονα μία εξαιρετική θέα της νήσου Σφακτηρίας. </Mon_Name>
			<Mon_Name Name="Το Παλαιόκαστρο"> Βόρεια της Πύλου, στον εξαιρετικής ομορφιάς όρμο της Βοϊδοκοιλιάς δεσπόζει το Παλαιόκαστρο, προσφέροντας μία μαγευτική θέα προς το Ιόνιο Πέλαγος. Το Παλαιόκαστρο ή Παλιοναβαρίνο χτίστηκε το 1287, στην οχυρή θέση της αρχαίας ακρόπολης της Πύλου. Το Παλαιόκαστρο διαδραμάτισε σπουδαίο ρόλο σε όλα τα πολεμικά γεγονότα της Πύλου, μέχρι το κτίσιμο του Νιόκαστρου, στη νότια πλευρά του λιμανιού, έπειτα από προσχώσεις στο στενό της Συκιάς από του Τούρκους. </Mon_Name>
			<Mon_Name Name="Το Νιόκαστρο"> Στη νότια είσοδο του λιμανιού, πάνω στα βράχια, είναι χτισμένο το επιβλητικό Νιόκαστρο. Η ονομασία «Νιόκαστρο» έρχεται σε αντιδιαστολή με το προγενέστερο φρούριο «Παλαιόκαστρο». Μέσα στο χώρο του κάστρου, μπορείτε να δείτε εκτός των άλλων την Ακρόπολη, το ναό της Μεταμόρφωσης του Σωτήρος, καθώς και να θαυμάσετε την πλούσια συλλογή του Γάλλου φιλέλληνα Rene Puaux. </Mon_Name>
		</Monuments>
		<Arounds>
			<Around Name="Μεθώνη"> Στο νοτιοδυτικό άκρο του νομού Μεσσηνίας και σε απόσταση 61 χλμ από την πόλη της Καλαμάτας βρίσκεται η Μεθώνη. Η Μεθώνη είναι μία όμορφη παραλιακή κωμόπολη με μοναδικά αξιοθέατα. Τους καλοκαιρινούς μήνες προσελκύει πλήθος επισκεπτών, καθώς ενδείκνυται για ήσυχες οικογενειακές διακοπές. Σύμφωνα με τον Παυσανία το πρώτο όνομα της πόλης ήταν Πήδασος. Ο Όμηρος την αναφέρει σαν μία από τις επτά πόλεις που είχε τάξει ο Αγαμέμνονας στον Αχιλλέα κατά τη διάρκεια του Τρωικού Πολέμου. </Around>
		</Arounds>
		<Beaches>
			<Beach Name="Παραλία Γιάλοβας"> Είναι μία εκτεταμένη αμμώδης παραλία με καταγάλανα νερά. Σήμα κατατεθέν της παραλίας είναι το ναυαγισμένο βαπόρι. Εδώ μπορείτε να απολαύσετε το μπάνιο σας, να κάνετε ηλιοθεραπεία, αλλά και να νοικιάσετε wind surf και κανό, προκειμένου να επιδοθείτε σε θαλάσσιες δραστηριότητες. Ακριβώς πάνω από την παραλία υπάρχουν εστιατόρια και καφετέριες, όπου μπορείτε να απολαύσετε το φαγητό ή τον καφέ σας. </Beach>
			<Beach Name="Παραλία Βοϊδοκοιλιάς"> Είναι αναμφισβήτητα η πιο δημοφιλής παραλία ολόκληρου του νομού Μεσσηνίας. Πρόκειται για μία παραλία αποτελούμενη από ψιλή άμμο, που σχηματίζει έναν σχεδόν ολοστρόγγυλο κόλπο, περικλείοντας μέσα του πεντακάθαρα γαλαζοπράσινα νερά. </Beach>
			<Beach Name="Παραλία Χρυσή ’μμος"> Πρόκειται για μία όμορφη, ήσυχη παραλία στρωμένη με ψιλή άμμο, με υπέροχη θέα στον κόλπο του Ναβαρίνου και τη νήσο Σφακτηρία. Κοντά στην παραλία θα βρείτε camping. </Beach>
		</Beaches>
		<Routing>
			<Distance From="Αθήνα" Value="320">
				<Routes>
					<Route> Από την Αθήνα μπορείτε να φτάσετε στην Πύλο αν ακολουθήσετε την Ε.Ο. Αθηνών-Κορίνθου-Τριπόλεως, και έπειτα ακολουθήσετε τη διαδρομή Τρίπολη Μεγαλόπολη- Καλαμάτα. Αφού φτάσετε στην Καλαμάτα, ακολουθείτε τη σήμανση προς Πύλο. </Route>
					<Route> Καθημερινά εκτελούνται δρομολόγια του ΚΤΕΛ από την Αθήνα. </Route>
				</Routes>
