=== GeorgeAlexandrakis93/XML/Part 1/Restaurant_Catalogue.dtd
<?xml version="1.0" encoding="ISO-8859-7" ?>

<!ELEMENT Catalogue (Basic_Menu, Special_Offer_Menu*)>
<!ELEMENT Basic_Menu (Dish+)>
<!ELEMENT Dish (Name, Category, Ingredient+, Price)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Category EMPTY>
<!ELEMENT Ingredient (Ingredient_Name)>
<!ELEMENT Ingredient_Name (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Special_Offer_Menu EMPTY>
<!ATTLIST Dish 
	Type (Normal | Sweet) #REQUIRED
	Code ID #REQUIRED>
<!ATTLIST Name
	Spicy (Yes | No) #IMPLIED
	Description CDATA #IMPLIED>
<!ATTLIST Category
	Type (Main_Dish | Appetizer | Dessert | Salad) #REQUIRED>
<!ATTLIST Ingredient
	Ingredient_Category (Chilled | Fresh | Packaged) #IMPLIED	
	Necessary (Yes | No) #REQUIRED>
<!ATTLIST Special_Offer_Menu
	idref1 IDREF #REQUIRED
	idref2 IDREF #REQUIRED
	Total_Price CDATA #REQUIRED>

=== GeorgeAlexandrakis93/XML/Part 1/Valid_Catalogue.xml
<?xml version="1.0" encoding="ISO-8859-7" ?>
<!DOCTYPE Catalogue SYSTEM "Restaurant_Catalogue.dtd">

<Catalogue>
    <Basic_Menu>
        <Dish Type="Normal" Code="a1">
            <Name Spicy="Yes" Description="Συνοδεύεται με ρύζι"> Μπούτι κοτόπουλο </Name>
            <Category Type="Main_Dish"/>
            <Ingredient Ingredient_Category="Fresh" Necessary="Yes"> <Ingredient_Name> Κοτόπουλο </Ingredient_Name> </Ingredient>
            <Ingredient Ingredient_Category="Fresh" Necessary="No"> <Ingredient_Name> Ρύζι </Ingredient_Name> </Ingredient>
            <Price> 8ευρώ </Price>
        </Dish>
        <Dish Type="Normal" Code="a2">
            <Name Spicy="No"> Παστίτσιο </Name>
            <Category Type="Main_Dish"/>
            <Ingredient Ingredient_Category="Fresh" Necessary="Yes"> <Ingredient_Name> Μακαρόνια </Ingredient_Name> </Ingredient>
            <Ingredient Ingredient_Category="Fresh" Necessary="Yes"> <Ingredient_Name> Μπεσαμέλ </Ingredient_Name> </Ingredient>
            <Price> 8ευρώ </Price>
        </Dish>
		<Dish Type="Normal" Code="a3">
            <Name Spicy="No" Description="Η κλασική"> Σαλάτα του Σεφ </Name>
            <Category Type="Salad"/>
            <Ingredient Ingredient_Category="Fresh" Necessary="Yes"> <Ingredient_Name> Ντομάτα </Ingredient_Name> </Ingredient>
            <Ingredient Ingredient_Category="Fresh" Necessary="Yes"> <Ingredient_Name> Αυγά </Ingredient_Name> </Ingredient>
            <Price> 5ευρώ </Price>
        </Dish>
		<Dish Type="Sweet" Code="a4">
            <Name Spicy="No"> Σουφλέ σοκολάτα </Name>
            <Category Type="Dessert"/>
            <Ingredient Ingredient_Category="Fresh" Necessary="Yes"> <Ingredient_Name> Κουβερτούρα </Ingredient_Name> </Ingredient>
            <Ingredient Ingredient_Category="Fresh" Necessary="Yes"> <Ingredient_Name> Ζάχαρη </Ingredient_Name> </Ingredient>
            <Price> 4ευρώ </Price>
        </Dish>
    </Basic_Menu>
	<Special_Offer_Menu idref1="a1" idref2="a4" Total_Price="10ευρώ"/>
	<Special_Offer_Menu idref1="a2" idref2="a3" Total_Price="10ευρώ"/>	
</Catalogue>
